-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 22:25:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema analizarapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema analizarapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analizarapp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `analizarapp` ;

-- -----------------------------------------------------
-- Table `analizarapp`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analizarapp`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` CHAR(50) NOT NULL,
  `apellido` CHAR(50) NOT NULL,
  `email` CHAR(50) NOT NULL,
  `celular` CHAR(50) NOT NULL,
  `habilitado` TINYINT(1) NOT NULL,
  `fechaalta` DATE NOT NULL,
  `contraseña` CHAR(30) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `analizarapp`.`medidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analizarapp`.`medidor` (
  `idmedidor` INT NOT NULL,
  `usuario` INT NOT NULL,
  `nombre` CHAR(50) NOT NULL,
  `detalle` CHAR(50) NOT NULL,
  PRIMARY KEY (`idmedidor`),
  INDEX `usuario` (`usuario` ASC) VISIBLE,
  CONSTRAINT `medidor_ibfk_1`
    FOREIGN KEY (`usuario`)
    REFERENCES `analizarapp`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `analizarapp`.`alertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analizarapp`.`alertas` (
  `idalerta` INT NOT NULL,
  `medidor` INT NOT NULL,
  `valor` INT NOT NULL,
  `fechaalta` DATE NOT NULL,
  `estado` CHAR(30) NOT NULL,
  PRIMARY KEY (`idalerta`),
  INDEX `medidor` (`medidor` ASC) VISIBLE,
  CONSTRAINT `alertas_ibfk_1`
    FOREIGN KEY (`medidor`)
    REFERENCES `analizarapp`.`medidor` (`idmedidor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `analizarapp`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analizarapp`.`consumo` (
  `idconsumo` INT NOT NULL,
  `medidor` INT NOT NULL,
  `fechademedicion` DATE NOT NULL,
  `consumo` INT NOT NULL,
  PRIMARY KEY (`idconsumo`),
  INDEX `medidor` (`medidor` ASC) VISIBLE,
  CONSTRAINT `consumo_ibfk_1`
    FOREIGN KEY (`medidor`)
    REFERENCES `analizarapp`.`medidor` (`idmedidor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
